services:
  db_kids:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kids_english_app
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql
      # ESTA LÍNEA ES LA MAGIA: Carga tus tablas automáticamente
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web_kids:
    image: php:8.2-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db_kids
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"